---
###############################################################################
# HAProxy Installation
###############################################################################

- import_tasks: 01-install.yml

###############################################################################
# HAProxy Configuration
###############################################################################

- import_tasks: 02-configure.yml

###############################################################################
# HAProxy Service
###############################################################################

- import_tasks: 03-service.yml

###############################################################################
# HAProxy Validation
###############################################################################

- import_tasks: 04-validation.yml
