---
###############################################################################
# Common Configuration
###############################################################################

- hosts: all
  become: yes

  roles:
    - common

###############################################################################
# Monitor Setup
###############################################################################

- hosts: monitor
  become: yes

  roles:
    - monitor

###############################################################################
# Primary Setup
###############################################################################

- hosts: primary
  become: yes

  roles:
    - primary

###############################################################################
# Standby Setup
###############################################################################

- hosts: standby
  become: yes
  serial: 1

  roles:
    - standby

###############################################################################
# Deploy pgcheck Service
###############################################################################

- hosts: primary:standby
  become: yes

  roles:
    - pgcheck

###############################################################################
# Deploy HAProxy
###############################################################################

- hosts: haproxy
  become: yes

  roles:
    - haproxy

###############################################################################
# Deploy PgBouncer
###############################################################################

- hosts: pgbouncer
  become: yes

  roles:
    - pgbouncer

###############################################################################
# Validate Complete Cluster
###############################################################################
#
#- hosts: monitor
#  become: yes
#
#  roles:
#    - validation
