---
###############################################################################
# PostgreSQL
###############################################################################

postgres_version: 17

postgres_service: postgresql

postgresql_bin_dir: "/usr/lib/postgresql/{{ postgres_version }}/bin"

###############################################################################
# Directories
###############################################################################

dr_pgdata: "/var/lib/postgresql/{{ postgres_version }}/main"

dr_archive_dir: "/var/lib/postgresql/archive"

###############################################################################
# HAProxy
###############################################################################

haproxy_host: "{{ groups['haproxy'][0] }}"

haproxy_port: 5000

###############################################################################
# Replication
###############################################################################

replication_user: postgres

replication_slot: dr_replica_slot

###############################################################################
# Validation
###############################################################################

pg_isready_timeout: 60
