
---
- name: Enable common configuration directory
  lineinfile:
    path: "{{ postgres_pgdata }}/postgresql.conf"
    regexp: "^#?include_dir"
    line: "include_dir = '/etc/postgresql/17/common/conf.d'"

  notify:
    - restart postgres

