---
- name: reload postgres
  become: yes
  become_user: postgres

  shell: |
    {{ pg_ctl_path }} reload \
      -D {{ postgres_pgdata }}

  changed_when: false

- name: restart postgres
  systemd:
    name: "{{ postgres_service_name }}"
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
