---
- name: Enable common configuration directory
  lineinfile:
    path: "/etc/postgresql/17/main/postgresql.conf"
    regexp: "^#?include_dir"
    line: "include_dir = '/etc/postgresql/17/common/conf.d'"

  notify:
    - restart postgres
