---
###############################################################################
# Phase 1 : Prerequisites
###############################################################################

- import_tasks: 01-prerequisites.yml

###############################################################################
# Phase 2 : Base Backup
###############################################################################

- import_tasks: 02-basebackup.yml

###############################################################################
# Phase 3 : Configure Standby
###############################################################################

- import_tasks: 03-configure.yml
- import_tasks: 03.1-configure.yml
- import_tasks: 03.2-configure.yml

###############################################################################
# Phase 4 : Start PostgreSQL
###############################################################################

- import_tasks: 04-start.yml

###############################################################################
# Phase 5 : Validate DR Replica
###############################################################################

- import_tasks: 05-validation.yml
