---


########################
#adding postgresql repo
####################

- import_tasks: 00-repo.yml


###############################################################################
# PgBouncer Installation
###############################################################################

- import_tasks: 01-install.yml

###############################################################################
# PgBouncer Configuration
###############################################################################

- import_tasks: 02-configure.yml

###############################################################################
# PgBouncer Authentication
###############################################################################

- import_tasks: 03-auth.yml

###############################################################################
# PgBouncer Service
###############################################################################

- import_tasks: 04-service.yml

###############################################################################
# PgBouncer Validation
###############################################################################

- import_tasks: 05-validation.yml

###############################################################################
# PgBouncer Summary
###############################################################################

- import_tasks: 06-show-status.yml
