---
###############################################################################
# Enable pgcheck
###############################################################################

- name: Enable pgcheck
  service:
    name: "{{ pgcheck_service }}"
    enabled: yes
    state: started
